# Generated by Django 5.1.5 on 2025-01-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSHSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "settings_name",
                    models.CharField(
                        help_text="Enter the unique settings name, This will be used to connect to each router/probe",
                        max_length=255,
                    ),
                ),
                ("port", models.PositiveIntegerField(default=22)),
                ("username", models.CharField(default="txfiber", max_length=255)),
                ("password", models.CharField(default="southtx956", max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="probe",
            name="name",
            field=models.CharField(
                help_text="Enter the unique hostname of the router, e.g., ABC-100.",
                max_length=100,
                unique=True,
                verbose_name="Router Host Name",
            ),
        ),
        migrations.AlterField(
            model_name="probe",
            name="type",
            field=models.CharField(
                choices=[
                    ("JUNIPER", "Juniper"),
                    ("CISCO", "Cisco"),
                    ("MIKROTIK", "Mikrotik"),
                    ("OTHER", "Other"),
                ],
                help_text="Select the model of the router, e.g., JUNIPER or Other.",
                max_length=20,
                verbose_name="Router Model",
            ),
        ),
    ]
