# Generated by Django 5.1.5 on 2025-01-19 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_sshsettings_alter_probe_name_alter_probe_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Router",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("JUNIPER", "Juniper"),
                            ("CISCO", "Cisco"),
                            ("MIKROTIK", "Mikrotik"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Select the model of the router, e.g., JUNIPER or Other.",
                        max_length=20,
                        verbose_name="Router Model",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the unique hostname of the router, e.g., ABC-100.",
                        max_length=100,
                        unique=True,
                        verbose_name="Router Host Name",
                    ),
                ),
                (
                    "asn",
                    models.PositiveIntegerField(
                        help_text="Enter the Autonomous System Number (ASN) of the probe. Must be a valid ASN.",
                        verbose_name="Autonomous System Number",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        help_text="Enter a valid IP address of the probe (IPv4 or IPv6).",
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        choices=[("v4", "IPv4"), ("v6", "IPv6")],
                        help_text="Specify whether the IP version is IPv4 or IPv6. Ensure it matches the IP format.",
                        max_length=2,
                        verbose_name="IP Version",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Enter the city where the probe is located. Only alphabetic characters are allowed.",
                        max_length=100,
                        verbose_name="City",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Enter the state where the probe is located (optional).",
                        max_length=100,
                        null=True,
                        verbose_name="State",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Enter the country where the probe is located (optional).",
                        max_length=100,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                (
                    "ssh_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.sshsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Probe",
                "verbose_name_plural": "Probes",
                "ordering": ["type", "name"],
            },
        ),
        migrations.DeleteModel(
            name="Probe",
        ),
        migrations.AddConstraint(
            model_name="router",
            constraint=models.UniqueConstraint(
                fields=("asn", "ip"), name="unique_asn_ip"
            ),
        ),
    ]
