# Generated by Django 5.1.5 on 2025-01-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_router_delete_probe_router_unique_asn_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sshsettings",
            name="settings_name",
            field=models.CharField(
                default="default",
                help_text="Enter the unique settings name, This will be used to connect to each router/probe",
                max_length=255,
                unique=True,
            ),
        ),
    ]
