# Generated by Django 5.1.5 on 2025-01-28 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sshsettings_settings_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter the command category', max_length=100, null=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, help_text='Enter the city where the probe is located. Only alphabetic characters are allowed', max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, help_text='Enter the state where the probe is located (optional)', max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, help_text='Enter the country where the probe is located (optional)', max_length=100, null=True, verbose_name='Country')),
            ],
        ),
        migrations.AlterModelOptions(
            name='router',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Router', 'verbose_name_plural': 'Routers'},
        ),
        migrations.AlterModelOptions(
            name='sshsettings',
            options={'verbose_name': 'SSH Settings', 'verbose_name_plural': 'SSH Settings'},
        ),
        migrations.AlterField(
            model_name='router',
            name='city',
            field=models.CharField(blank=True, help_text='Enter the city where the probe is located. Only alphabetic characters are allowed.', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='router',
            name='ssh_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sshsettings', verbose_name='SSH Settings'),
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Enter the command label', max_length=100, null=True, verbose_name='Label')),
                ('command', models.CharField(blank=True, help_text='Enter the command', max_length=100, null=True, verbose_name='Command')),
                ('purpose', models.CharField(blank=True, help_text='Enter the purpose', max_length=100, null=True, verbose_name='Purpose')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
