# Generated by Django 4.2.18 on 2025-01-29 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_datacenter_alter_router_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='city',
        ),
        migrations.RemoveField(
            model_name='router',
            name='country',
        ),
        migrations.RemoveField(
            model_name='router',
            name='state',
        ),
        migrations.AddField(
            model_name='router',
            name='datacenter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.datacenter', verbose_name='Data Center Location'),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='city',
            field=models.CharField(default='Harlington', help_text='Enter the city where the probe is located. Only alphabetic characters are allowed', max_length=100, verbose_name='City'),
        ),
    ]
