# Generated by Django 4.2.18 on 2025-01-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_router_city_remove_router_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='datacenter',
            options={'ordering': ['city'], 'verbose_name': 'Data Center', 'verbose_name_plural': 'Data Centers'},
        ),
    ]
