# Generated by Django 4.2.18 on 2025-01-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_category_options_alter_datacenter_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='datacenter',
            constraint=models.UniqueConstraint(fields=('city', 'state', 'country'), name='unique_datacenter'),
        ),
    ]
