# Generated by Django 4.2.18 on 2025-01-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_datacenter_unique_datacenter'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datacenter',
            name='unique_datacenter',
        ),
        migrations.AddConstraint(
            model_name='datacenter',
            constraint=models.UniqueConstraint(fields=('city', 'state'), name='unique_datacenter'),
        ),
    ]
