# Generated by Django 4.2.18 on 2025-01-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_datacenter_unique_datacenter_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sshsettings',
            constraint=models.UniqueConstraint(fields=('port', 'username', 'password'), name='unique_settings'),
        ),
    ]
