# Generated by Django 5.1.5 on 2025-02-01 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sshsettings_unique_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(help_text='Command executed by the user')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the command was executed')),
                ('output', models.TextField(blank=True, help_text='Output result of the command execution', null=True)),
                ('user', models.ForeignKey(help_text='User who executed the command', on_delete=django.db.models.deletion.CASCADE, related_name='command_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Command History',
                'verbose_name_plural': 'Command Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
