# Generated by Django 5.1.5 on 2025-02-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_commandhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandhistory',
            name='output',
            field=models.JSONField(blank=True, help_text='Output result of the command execution stored as JSON', null=True),
        ),
    ]
