# Generated by Django 5.1.5 on 2025-02-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_commandhistory_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Enter the command label', max_length=100, null=True, verbose_name='Label')),
                ('command', models.CharField(blank=True, help_text='Enter the command', max_length=100, null=True, verbose_name='Command')),
                ('purpose', models.CharField(blank=True, help_text='Enter the purpose', max_length=100, null=True, verbose_name='Purpose')),
            ],
        ),
    ]
