# Generated by Django 5.1.5 on 2025-02-02 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_popularcommand_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularcommand',
            name='command',
            field=models.OneToOneField(help_text='Each command can be executed only once in the popular commands list.', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.command'),
        ),
    ]
