# Generated by Django 4.2.18 on 2025-02-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_popularcommand_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandhistory',
            name='device',
            field=models.ForeignKey(default=None, help_text='Device where command was executed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_history_devices', to='app.router'),
        ),
    ]
