# Generated by Django 4.2.18 on 2025-02-06 09:52

from django.db import migrations

def create_default_sshsettings(apps, schema_editor):
    SSHSettings = apps.get_model('app', 'SSHSettings')
    # Use get_or_create to ensure we only create it if it doesn't exist
    SSHSettings.objects.get_or_create(
        settings_name="default",
        defaults={
            "port": 22,
            "username": "txfiber",
            "password": "southtx956"
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_commandhistory_device'),
    ]

    operations = [
        migrations.RunPython(create_default_sshsettings),
    ]
