# Generated by Django 4.2.18 on 2025-02-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_populate_default_sshsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandhistory',
            name='command',
            field=models.CharField(help_text='Command executed by the user', max_length=500),
        ),
        migrations.AlterField(
            model_name='commandhistory',
            name='output',
            field=models.TextField(default='PING OK', help_text='Output result of the command execution'),
        ),
    ]
