# Generated by Django 4.2.18 on 2025-03-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_router_consecutive_failures_router_cpu_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='last_pings',
            field=models.CharField(default='', max_length=3),
        ),
    ]
