# Generated by Django 4.2.18 on 2025-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_router_last_pings'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='summary',
            field=models.CharField(blank=True, help_text='Enter the summary of the category', max_length=500, null=True, verbose_name='Category Summary'),
        ),
    ]
