# Generated by Django 4.2.18 on 2025-03-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_category_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
