# Generated by Django 4.2.18 on 2025-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AddField(
            model_name='router',
            name='last_3_latency',
            field=models.JSONField(default=dict, help_text='Last 3 latency values in ms'),
        ),
    ]
