# Generated by Django 4.2.18 on 2025-03-10 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_delete_testmodel_router_last_3_latency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='configuration/')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.router')),
            ],
        ),
    ]
