# Generated by Django 5.1.5 on 2025-03-11 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_configuration_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latency', models.FloatField(help_text='Latency in ms', null=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.router')),
            ],
            options={
                'verbose_name': 'Latency',
                'verbose_name_plural': 'Latencies',
                'ordering': ['-created_at'],
            },
        ),
    ]
