# Generated by Django 4.2.18 on 2025-03-12 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alertrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertrule',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='alertrule',
            name='last_triggered',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
