# Generated by Django 4.2.18 on 2025-03-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_alertrule_options_alertrule_last_triggered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='syslog_strings',
            field=models.TextField(blank=True, default='OSPF,BGP', help_text='Strings to match for syslog events separated by commas (e.g., OSPF,BGP)', null=True),
        ),
    ]
