# Generated by Django 4.2.18 on 2025-03-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_alertrule_syslog_strings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='last_triggered',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
