# Generated by Django 4.2.18 on 2025-03-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_router_last_pings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='version',
            field=models.CharField(choices=[('v4', 'IPv4'), ('v6', 'IPv6')], default='v4', help_text='Specify whether the IP version is IPv4 or IPv6. Ensure it matches the IP format.', max_length=2, verbose_name='IP Version'),
        ),
    ]
