# Generated by Django 5.1.5 on 2025-03-15 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alert_hostname_alert_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='router',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.router'),
        ),
    ]
