# Generated by Django 4.2.18 on 2025-03-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alert_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='only_monitor',
            field=models.BooleanField(default=False, help_text='Only monitor this device using ICMP without downloading configurations'),
        ),
    ]
