# Generated by Django 4.2.18 on 2025-03-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_configurationbackuphistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationbackuphistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Configuration Backup History', 'verbose_name_plural': 'Configuration Backup Histories'},
        ),
    ]
